In [3]:
import pandas as pd

In [4]:
df=pd.read_csv('POWER_Point_Daily_19900101_20221231_007d93N_081d04E_LST.csv')
df1=pd.read_csv('sri_lanka_north_central_polonnaruwa_1_month_rainfall_aggregate (1).csv')

In [5]:
df

,YEAR,DOY,T2M,T2MDEW,TS,T2M_RANGE,T2M_MAX,T2M_MIN,QV2M,RH2M,PS,WS2M,WS2M_MAX,WS2M_MIN,GWETTOP,GWETROOT,GWETPROF
0,1990,1,25.44,22.18,25.69,5.60,28.81,23.20,16.72,82.69,100.48,2.69,4.34,1.45,0.58,0.56,0.57
1,1990,2,25.36,21.26,25.66,6.05,28.75,22.70,15.75,78.56,100.49,3.00,4.42,1.62,0.57,0.55,0.56
2,1990,3,25.83,22.50,26.02,5.04,28.83,23.80,17.03,82.31,100.52,3.44,4.93,2.02,0.56,0.55,0.56
3,1990,4,25.23,23.55,25.27,2.93,26.98,24.05,18.13,90.44,100.59,4.06,5.86,2.27,0.67,0.57,0.57
4,1990,5,24.89,23.40,24.91,2.98,26.63,23.64,18.01,91.44,100.64,4.47,5.88,3.12,0.72,0.61,0.59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12048,2022,361,25.50,23.43,25.68,4.90,28.40,23.51,18.01,88.62,100.73,2.16,3.28,1.40,0.89,0.93,0.92
12049,2022,362,25.40,23.54,25.63,4.67,28.15,23.48,18.07,89.62,100.82,2.60,4.31,1.30,0.88,0.91,0.91
12050,2022,363,25.30,22.69,25.23,4.63,28.13,23.50,17.15,85.81,100.95,3.09,4.66,2.16,0.88,0.91,0.91
12051,2022,364,24.70,21.76,24.69,4.75,27.51,22.76,16.17,84.06,101.02,2.85,4.33,1.78,0.87,0.90,0.90
12052,2022,365,24.49,21.83,24.62,5.05,27.40,22.34,16.30,85.44,100.98,2.43,3.84,1.58,0.87,0.89,0.89

In [6]:
df['Date'] = pd.to_datetime(df['YEAR'].astype(str) + '-' + df['DOY'].astype(str), format='%Y-%j').dt.strftime('%Y-%m-%d')

In [7]:
df=df.drop(['YEAR','DOY'], axis=1)

In [8]:
df1.head()

         Date  1_month_rainfall_aggregate  1_month_rainfall_aggregate_avg
0  1990-01-01                    246.1120                        301.2839
1  1990-01-11                    201.8966                        237.2716
2  1990-01-21                    192.2845                        180.1767
3  1990-02-01                     40.6034                        143.8716
4  1990-02-11                     15.9914                        107.4868

In [9]:
df.head()

,T2M,T2MDEW,TS,T2M_RANGE,T2M_MAX,T2M_MIN,QV2M,RH2M,PS,WS2M,WS2M_MAX,WS2M_MIN,GWETTOP,GWETROOT,GWETPROF,Date
0,25.44,22.18,25.69,5.60,28.81,23.20,16.72,82.69,100.48,2.69,4.34,1.45,0.58,0.56,0.57,1990-01-01
1,25.36,21.26,25.66,6.05,28.75,22.70,15.75,78.56,100.49,3.00,4.42,1.62,0.57,0.55,0.56,1990-01-02
2,25.83,22.50,26.02,5.04,28.83,23.80,17.03,82.31,100.52,3.44,4.93,2.02,0.56,0.55,0.56,1990-01-03
3,25.23,23.55,25.27,2.93,26.98,24.05,18.13,90.44,100.59,4.06,5.86,2.27,0.67,0.57,0.57,1990-01-04
4,24.89,23.40,24.91,2.98,26.63,23.64,18.01,91.44,100.64,4.47,5.88,3.12,0.72,0.61,0.59,1990-01-05

In [10]:
import numpy as np

df['Date'] = pd.to_datetime(df['Date'])

def map_to_closest_special_date(date):
    month_start = date.replace(day=1)
    special_dates = [month_start, month_start + pd.DateOffset(days=10), month_start + pd.DateOffset(days=20)]
    closest_date = min(special_dates, key=lambda x: abs(date - x))
    return closest_date

df['Date'] =df['Date'].apply(map_to_closest_special_date)

mapped_data = df.groupby('Date').agg('mean')

In [11]:
mapped_data.head(20)

,T2M,T2MDEW,TS,T2M_RANGE,T2M_MAX,T2M_MIN,QV2M,RH2M,PS,WS2M,WS2M_MAX,WS2M_MIN,GWETTOP,GWETROOT,GWETPROF
Date,,,,,,,,,,,,,,,
1990-01-01,25.438333,22.776667,25.558333,4.303333,27.983333,23.680000,17.335000,85.625000,100.558333,3.731667,5.241667,2.311667,0.646667,0.578333,0.576667
1990-01-11,24.637000,21.199000,24.792000,5.206000,27.725000,22.518000,15.753000,81.599000,100.673000,2.985000,4.245000,2.019000,0.714000,0.668000,0.659000
1990-01-21,24.559333,20.202667,24.854000,7.052667,28.532000,21.480000,14.798667,77.519333,100.670000,2.586667,3.802667,1.584667,0.586000,0.571333,0.580667
1990-02-01,25.503333,20.528333,26.280000,7.721667,29.900000,22.180000,15.055000,75.051667,100.713333,3.031667,4.255000,1.913333,0.503333,0.521667,0.528333
1990-02-11,27.009000,22.133000,27.867000,6.830000,30.994000,24.167000,16.651000,75.986000,100.651000,3.634000,4.939000,2.305000,0.456000,0.490000,0.497000
1990-02-21,28.376667,21.724167,29.860000,10.253333,34.106667,23.852500,16.311667,70.110833,100.392500,2.057500,3.388333,0.815000,0.412500,0.455000,0.461667
1990-03-01,28.811667,21.048333,30.451667,10.843333,34.938333,24.090000,15.705000,66.031667,100.418333,2.248333,3.940000,0.891667,0.386667,0.433333,0.441667
1990-03-11,28.986000,21.963000,30.569000,9.245000,34.398000,25.149000,16.530000,68.319000,100.690000,2.465000,4.013000,1.301000,0.402000,0.425000,0.428000
1990-03-21,28.994000,22.630000,30.425333,8.509333,33.960667,25.452000,17.228000,70.732667,100.459333,2.598667,4.107333,1.292667,0.435333,0.450667,0.448000
1990-04-01,29.620000,22.828333,30.996667,8.541667,34.570000,26.033333,17.466667,69.103333,100.305000,2.273333,3.601667,0.991667,0.406667,0.433333,0.440000
1990-04-11,29.743000,22.606000,31.087000,8.380000,34.585000,26.206000,17.262000,67.575000,100.140000,2.037000,3.177000,0.899000,0.387000,0.418000,0.424000
1990-04-21,30.515714,22.304286,32.147143,10.481429,36.416429,25.933571,16.946429,64.496429,100.229286,2.372143,3.811429,1.195000,0.391429,0.415714,0.417143
1990-05-01,29.385000,23.150000,30.380000,8.025000,34.055000,26.028333,17.871667,71.208333,100.033333,2.758333,4.296667,1.121667,0.473333,0.430000,0.423333
1990-05-11,28.252000,24.018000,28.577000,6.306000,31.902000,25.597000,18.829000,78.954000,99.960000,2.959000,4.575000,1.635000,0.538000,0.520000,0.509000
1990-05-21,28.337333,23.161333,29.001333,6.902000,32.362667,25.461333,17.817333,74.880000,100.178667,5.341333,7.059333,3.605333,0.482000,0.496000,0.495333
1990-06-01,28.138333,22.553333,28.725000,6.756667,32.096667,25.341667,17.170000,72.971667,100.106667,5.430000,6.740000,4.376667,0.461667,0.480000,0.480000
1990-06-11,28.169000,22.333000,28.879000,7.166000,32.387000,25.221000,16.937000,72.227000,100.195000,6.063000,7.415000,4.675000,0.434000,0.467000,0.472000
1990-06-21,29.186429,22.172857,29.980714,8.835714,34.427857,25.591429,16.792857,68.129286,100.136429,5.622143,6.966429,4.232857,0.408571,0.441429,0.446429
1990-07-01,27.988333,21.423333,28.885000,7.453333,32.315000,24.860000,16.001667,69.258333,100.291667,5.375000,6.921667,3.990000,0.406667,0.435000,0.436667
1990-07-11,27.896000,21.753000,28.740000,7.779000,32.407000,24.634000,16.313000,71.189000,100.397000,4.492000,5.670000,3.185000,0.400000,0.421000,0.425000

In [12]:
df1['Date']=pd.to_datetime(df1['Date'])
merged_df = pd.merge(mapped_data, df1, on='Date', how='left')

In [13]:
merged_df.head()

,Date,T2M,T2MDEW,TS,T2M_RANGE,T2M_MAX,T2M_MIN,QV2M,RH2M,PS,WS2M,WS2M_MAX,WS2M_MIN,GWETTOP,GWETROOT,GWETPROF,1_month_rainfall_aggregate,1_month_rainfall_aggregate_avg
0,1990-01-01,25.438333,22.776667,25.558333,4.303333,27.983333,23.680,17.335000,85.625000,100.558333,3.731667,5.241667,2.311667,0.646667,0.578333,0.576667,246.1120,301.2839
1,1990-01-11,24.637000,21.199000,24.792000,5.206000,27.725000,22.518,15.753000,81.599000,100.673000,2.985000,4.245000,2.019000,0.714000,0.668000,0.659000,201.8966,237.2716
2,1990-01-21,24.559333,20.202667,24.854000,7.052667,28.532000,21.480,14.798667,77.519333,100.670000,2.586667,3.802667,1.584667,0.586000,0.571333,0.580667,192.2845,180.1767
3,1990-02-01,25.503333,20.528333,26.280000,7.721667,29.900000,22.180,15.055000,75.051667,100.713333,3.031667,4.255000,1.913333,0.503333,0.521667,0.528333,40.6034,143.8716
4,1990-02-11,27.009000,22.133000,27.867000,6.830000,30.994000,24.167,16.651000,75.986000,100.651000,3.634000,4.939000,2.305000,0.456000,0.490000,0.497000,15.9914,107.4868

In [14]:
merged_df.isnull().sum()

Date                              0
T2M                               0
T2MDEW                            0
TS                                0
T2M_RANGE                         0
T2M_MAX                           0
T2M_MIN                           0
QV2M                              0
RH2M                              0
PS                                0
WS2M                              0
WS2M_MAX                          0
WS2M_MIN                          0
GWETTOP                           0
GWETROOT                          0
GWETPROF                          0
1_month_rainfall_aggregate        0
1_month_rainfall_aggregate_avg    0
dtype: int64

In [15]:
merged_df.tail()

,Date,T2M,T2MDEW,TS,T2M_RANGE,T2M_MAX,T2M_MIN,QV2M,RH2M,PS,WS2M,WS2M_MAX,WS2M_MIN,GWETTOP,GWETROOT,GWETPROF,1_month_rainfall_aggregate,1_month_rainfall_aggregate_avg
1183,2022-11-11,25.644000,23.425000,25.893,4.215000,28.122000,23.908000,18.037000,87.757000,100.457000,2.359000,3.611000,1.223000,0.860000,0.847000,0.834000,351.1379,324.5644
1184,2022-11-21,25.586429,22.733571,25.740,6.051429,28.937143,22.885714,17.322143,84.782857,100.367857,2.278571,3.516429,1.422857,0.830714,0.834286,0.837143,277.1724,337.5647
1185,2022-12-01,26.000000,23.490000,26.070,4.458333,28.548333,24.091667,18.116667,86.301667,100.401667,2.020000,3.313333,1.033333,0.836667,0.821667,0.816667,196.7241,341.2100
1186,2022-12-11,24.888000,22.236000,24.897,5.552000,28.002000,22.449000,16.815000,85.606000,100.295000,3.256000,4.643000,1.773000,0.825000,0.820000,0.821000,320.1293,356.7336
1187,2022-12-21,25.370667,23.525333,25.354,3.657333,27.567333,23.912000,18.173333,89.690000,100.420000,3.532667,5.275333,2.152667,0.875333,0.882000,0.874000,468.4052,339.5899

In [16]:
merged_df.to_csv('DSGP_Final_2.csv', index=False)